### ISSUE TITLE
BE: cafe, cafeImage에 uploaderDisplayName parameter 추가

### ISSUE THREAD

**Issue by inhibitor1217** [inhibitor1217/coffee-hmm#65]
해당 field는 실제로 api를 invoke한 user와는 관계없는, 그냥 string field (나중에 spec이 변경될 수도. 이 필드는 그냥 legacy로 남겨놓는 것이 좋을듯)

**Comment by inhibitor1217** [comment]
@jyuunnii table에 column을 추가하는 것 말고, 그냥 metadata 필드에 추가하는 것으로도 가능하긴 해요 (metadata는 json으로 serialize되어 저장됨) 지금 cafe와 cafe image에 모두 metadata field가 존재합니다.

**Comment by jyuunnii** [comment]
`creator` 로 `metadata` 필드에 추가했습니다 :)
